In [82]:
import pandas as pd
import numpy as np

## Extract inventario diario

In [83]:
df_inventario_diario = pd.read_csv('../data/fotografia_inventario_diario_sanitizado.csv')
display(df_inventario_diario.head(20))
display(df_inventario_diario.info())

         fecha    id_producto  stock_cierre     almacen
0   2025-11-29   PROD-CEMENTO           841    ALM-LIMA
1   2025-11-29  PROD-LADRILLO          1392    ALM-LIMA
2   2025-11-29     PROD-ACERO          1515    ALM-LIMA
3   2025-11-29     PROD-ARENA          1050  ALM-CALLAO
4   2025-11-30   PROD-CEMENTO          1245    ALM-LIMA
5   2025-11-30  PROD-LADRILLO          1043  ALM-CALLAO
6   2025-11-30     PROD-ACERO          1544  ALM-CALLAO
7   2025-11-30     PROD-ARENA          1195  ALM-CALLAO
8   2025-12-01   PROD-CEMENTO          1148  ALM-CALLAO
9   2025-12-01  PROD-LADRILLO           998    ALM-LIMA
10  2025-12-01     PROD-ACERO           948  ALM-CALLAO
11  2025-12-01     PROD-ARENA          1238  ALM-CALLAO
12  2025-12-02   PROD-CEMENTO           660  ALM-CALLAO
13  2025-12-02  PROD-LADRILLO           676    ALM-LIMA
14  2025-12-02     PROD-ACERO             0  ALM-CALLAO
15  2025-12-02     PROD-ARENA          1621    ALM-LIMA
16  2025-12-03   PROD-CEMENTO             0  ALM-CALLAO
17  2025-12-03  PROD-LADRILLO          1106    ALM-LIMA
18  2025-12-03     PROD-ACERO           759    ALM-LIMA
19  2025-12-03     PROD-ARENA           688    ALM-LIMA

<class 'pandas.DataFrame'>
RangeIndex: 720 entries, 0 to 719
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   fecha         720 non-null    str
 1   id_producto   720 non-null    str
 2   stock_cierre  720 non-null    int64
 3   almacen       720 non-null    str
dtypes: int64(1), str(3)
memory usage: 43.9 KB

None

#### ELiminar duplicados exactos

In [84]:
df_inventario_diario = df_inventario_diario.drop_duplicates(subset=['fecha', 'id_producto', 'stock_cierre' ,'almacen'], keep='first')
display(df_inventario_diario.head())

        fecha    id_producto  stock_cierre     almacen
0  2025-11-29   PROD-CEMENTO           841    ALM-LIMA
1  2025-11-29  PROD-LADRILLO          1392    ALM-LIMA
2  2025-11-29     PROD-ACERO          1515    ALM-LIMA
3  2025-11-29     PROD-ARENA          1050  ALM-CALLAO
4  2025-11-30   PROD-CEMENTO          1245    ALM-LIMA

#### Estandarizacion de fecha

In [85]:
df_inventario_diario["fecha"] = pd.to_datetime(df_inventario_diario["fecha"], format="mixed")
display(df_inventario_diario.info())

<class 'pandas.DataFrame'>
RangeIndex: 720 entries, 0 to 719
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   fecha         720 non-null    datetime64[us]
 1   id_producto   720 non-null    str
 2   stock_cierre  720 non-null    int64
 3   almacen       720 non-null    str
dtypes: datetime64[us](1), int64(1), str(2)
memory usage: 36.8 KB

None

#### Estandarizacion texto

In [86]:
df_inventario_diario['id_producto'] = df_inventario_diario['id_producto'].str.replace(' ', '').str.strip().str.upper()
df_inventario_diario['almacen'] = df_inventario_diario['almacen'].str.replace(' ', '').str.strip().str.upper()
display(df_inventario_diario.head())

       fecha    id_producto  stock_cierre     almacen
0 2025-11-29   PROD-CEMENTO           841    ALM-LIMA
1 2025-11-29  PROD-LADRILLO          1392    ALM-LIMA
2 2025-11-29     PROD-ACERO          1515    ALM-LIMA
3 2025-11-29     PROD-ARENA          1050  ALM-CALLAO
4 2025-11-30   PROD-CEMENTO          1245    ALM-LIMA

#### Coercion numerica

In [87]:
df_inventario_diario['stock_cierre'] = pd.to_numeric(df_inventario_diario['stock_cierre'], errors='coerce')
df_inventario_diario['stock_cierre'] = df_inventario_diario['stock_cierre'].fillna(0).astype(int)
df_inventario_diario.loc[df_inventario_diario['stock_cierre'] < 0, 'stock_cierre'] = 0
display(df_inventario_diario.head())

       fecha    id_producto  stock_cierre     almacen
0 2025-11-29   PROD-CEMENTO           841    ALM-LIMA
1 2025-11-29  PROD-LADRILLO          1392    ALM-LIMA
2 2025-11-29     PROD-ACERO          1515    ALM-LIMA
3 2025-11-29     PROD-ARENA          1050  ALM-CALLAO
4 2025-11-30   PROD-CEMENTO          1245    ALM-LIMA

## Extract ventas diarias

In [88]:
df_ventas_diarias = pd.read_csv('../data/ventas_diarias_sanitizado.csv')
display(df_ventas_diarias.head())
display(df_ventas_diarias.info())

        fecha    id_producto  cantidad_vendida    cliente_b2b estado_orden
0  2025-11-29   PROD-CEMENTO               108   RETAIL OMEGA   COMPLETADA
1  2025-11-29   PROD-CEMENTO               108   RETAIL OMEGA   COMPLETADA
2  2025-11-29   PROD-CEMENTO               108  INDEPENDIENTE   COMPLETADA
3  2025-11-29  PROD-LADRILLO               112  INDEPENDIENTE   COMPLETADA
4  2025-11-29  PROD-LADRILLO               112  INDEPENDIENTE   COMPLETADA

<class 'pandas.DataFrame'>
RangeIndex: 1344 entries, 0 to 1343
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   fecha             1344 non-null   str
 1   id_producto       1344 non-null   str
 2   cantidad_vendida  1344 non-null   int64
 3   cliente_b2b       1344 non-null   str
 4   estado_orden      1344 non-null   str
dtypes: int64(1), str(4)
memory usage: 113.7 KB

None

#### Eliminar duplicados

In [89]:
df_ventas_diarias.drop_duplicates(subset=['fecha', 'id_producto', 'cantidad_vendida', 'cliente_b2b', 'estado_orden'], keep='first')

,fecha,id_producto,cantidad_vendida,cliente_b2b,estado_orden
0,2025-11-29,PROD-CEMENTO,108,RETAIL OMEGA,COMPLETADA
2,2025-11-29,PROD-CEMENTO,108,INDEPENDIENTE,COMPLETADA
3,2025-11-29,PROD-LADRILLO,112,INDEPENDIENTE,COMPLETADA
5,2025-11-29,PROD-ACERO,423,CONSTRUCTORA ALFA,COMPLETADA
6,2025-11-29,PROD-ARENA,96,CONSTRUCTORA BETA,COMPLETADA
...,...,...,...,...,...
1338,2026-05-27,PROD-LADRILLO,70,RETAIL OMEGA,COMPLETADA
1340,2026-05-27,PROD-ACERO,126,INDEPENDIENTE,COMPLETADA
1341,2026-05-27,PROD-ACERO,126,CONSTRUCTORA ALFA,COMPLETADA
1342,2026-05-27,PROD-ACERO,126,CONSTRUCTORA BETA,COMPLETADA
1343,2026-05-27,PROD-ARENA,215,INDEPENDIENTE,COMPLETADA

#### Estandarizacion fecha

In [90]:
df_ventas_diarias['fecha'] = pd.to_datetime(df_ventas_diarias['fecha'], format='mixed')
df_ventas_diarias.info()

<class 'pandas.DataFrame'>
RangeIndex: 1344 entries, 0 to 1343
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   fecha             1344 non-null   datetime64[us]
 1   id_producto       1344 non-null   str
 2   cantidad_vendida  1344 non-null   int64
 3   cliente_b2b       1344 non-null   str
 4   estado_orden      1344 non-null   str
dtypes: datetime64[us](1), int64(1), str(3)
memory usage: 100.6 KB

#### Estandarizacion texto

In [91]:
df_ventas_diarias['id_producto'] = df_ventas_diarias['id_producto'].str.upper().str.replace(r'\s+', '', regex=True)
df_ventas_diarias.head()

       fecha    id_producto  cantidad_vendida    cliente_b2b estado_orden
0 2025-11-29   PROD-CEMENTO               108   RETAIL OMEGA   COMPLETADA
1 2025-11-29   PROD-CEMENTO               108   RETAIL OMEGA   COMPLETADA
2 2025-11-29   PROD-CEMENTO               108  INDEPENDIENTE   COMPLETADA
3 2025-11-29  PROD-LADRILLO               112  INDEPENDIENTE   COMPLETADA
4 2025-11-29  PROD-LADRILLO               112  INDEPENDIENTE   COMPLETADA

In [92]:
df_ventas_diarias['cliente_b2b'] = df_ventas_diarias['cliente_b2b'].str.upper().str.replace(r'\s\s+', '', regex=True).str.strip()
df_ventas_diarias.head(20)

        fecha    id_producto  cantidad_vendida        cliente_b2b estado_orden
0  2025-11-29   PROD-CEMENTO               108       RETAIL OMEGA   COMPLETADA
1  2025-11-29   PROD-CEMENTO               108       RETAIL OMEGA   COMPLETADA
2  2025-11-29   PROD-CEMENTO               108      INDEPENDIENTE   COMPLETADA
3  2025-11-29  PROD-LADRILLO               112      INDEPENDIENTE   COMPLETADA
4  2025-11-29  PROD-LADRILLO               112      INDEPENDIENTE   COMPLETADA
5  2025-11-29     PROD-ACERO               423  CONSTRUCTORA ALFA   COMPLETADA
6  2025-11-29     PROD-ARENA                96  CONSTRUCTORA BETA   COMPLETADA
7  2025-11-29     PROD-ARENA                96  CONSTRUCTORA BETA   COMPLETADA
8  2025-11-29     PROD-ARENA                96       RETAIL OMEGA   COMPLETADA
9  2025-11-30   PROD-CEMENTO                99  CONSTRUCTORA ALFA   COMPLETADA
10 2025-11-30   PROD-CEMENTO                99       RETAIL OMEGA   COMPLETADA
11 2025-11-30   PROD-CEMENTO                99       RETAIL OMEGA   COMPLETADA
12 2025-11-30  PROD-LADRILLO                92      INDEPENDIENTE   COMPLETADA
13 2025-11-30  PROD-LADRILLO                92       RETAIL OMEGA   COMPLETADA
14 2025-11-30  PROD-LADRILLO                92      INDEPENDIENTE   COMPLETADA
15 2025-11-30     PROD-ACERO               101  CONSTRUCTORA BETA   COMPLETADA
16 2025-11-30     PROD-ACERO               101  CONSTRUCTORA BETA   COMPLETADA
17 2025-11-30     PROD-ARENA               123      INDEPENDIENTE   COMPLETADA
18 2025-11-30     PROD-ARENA               123  CONSTRUCTORA BETA   COMPLETADA
19 2025-11-30     PROD-ARENA               123       RETAIL OMEGA   COMPLETADA

#### Conercion numerica

In [93]:
df_ventas_diarias['cantidad_vendida'] = pd.to_numeric(df_ventas_diarias['cantidad_vendida'], errors='coerce')
df_ventas_diarias['cantidad_vendida'] = df_ventas_diarias['cantidad_vendida'].fillna(0).astype(int)
df_ventas_diarias.loc[df_ventas_diarias['cantidad_vendida'] < 0, 'cantidad_vendida'] = 0
df_ventas_diarias.head(20)

        fecha    id_producto  cantidad_vendida        cliente_b2b estado_orden
0  2025-11-29   PROD-CEMENTO               108       RETAIL OMEGA   COMPLETADA
1  2025-11-29   PROD-CEMENTO               108       RETAIL OMEGA   COMPLETADA
2  2025-11-29   PROD-CEMENTO               108      INDEPENDIENTE   COMPLETADA
3  2025-11-29  PROD-LADRILLO               112      INDEPENDIENTE   COMPLETADA
4  2025-11-29  PROD-LADRILLO               112      INDEPENDIENTE   COMPLETADA
5  2025-11-29     PROD-ACERO               423  CONSTRUCTORA ALFA   COMPLETADA
6  2025-11-29     PROD-ARENA                96  CONSTRUCTORA BETA   COMPLETADA
7  2025-11-29     PROD-ARENA                96  CONSTRUCTORA BETA   COMPLETADA
8  2025-11-29     PROD-ARENA                96       RETAIL OMEGA   COMPLETADA
9  2025-11-30   PROD-CEMENTO                99  CONSTRUCTORA ALFA   COMPLETADA
10 2025-11-30   PROD-CEMENTO                99       RETAIL OMEGA   COMPLETADA
11 2025-11-30   PROD-CEMENTO                99       RETAIL OMEGA   COMPLETADA
12 2025-11-30  PROD-LADRILLO                92      INDEPENDIENTE   COMPLETADA
13 2025-11-30  PROD-LADRILLO                92       RETAIL OMEGA   COMPLETADA
14 2025-11-30  PROD-LADRILLO                92      INDEPENDIENTE   COMPLETADA
15 2025-11-30     PROD-ACERO               101  CONSTRUCTORA BETA   COMPLETADA
16 2025-11-30     PROD-ACERO               101  CONSTRUCTORA BETA   COMPLETADA
17 2025-11-30     PROD-ARENA               123      INDEPENDIENTE   COMPLETADA
18 2025-11-30     PROD-ARENA               123  CONSTRUCTORA BETA   COMPLETADA
19 2025-11-30     PROD-ARENA               123       RETAIL OMEGA   COMPLETADA

#### Merge ventas e inventario

In [94]:
display(df_ventas_diarias.info())
display(df_inventario_diario.info())

<class 'pandas.DataFrame'>
RangeIndex: 1344 entries, 0 to 1343
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   fecha             1344 non-null   datetime64[us]
 1   id_producto       1344 non-null   str
 2   cantidad_vendida  1344 non-null   int64
 3   cliente_b2b       1344 non-null   str
 4   estado_orden      1344 non-null   str
dtypes: datetime64[us](1), int64(1), str(3)
memory usage: 100.9 KB

None

<class 'pandas.DataFrame'>
RangeIndex: 720 entries, 0 to 719
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   fecha         720 non-null    datetime64[us]
 1   id_producto   720 non-null    str
 2   stock_cierre  720 non-null    int64
 3   almacen       720 non-null    str
dtypes: datetime64[us](1), int64(1), str(2)
memory usage: 37.0 KB

None

In [95]:
df_merge = pd.merge(df_ventas_diarias, df_inventario_diario, on=["fecha", "id_producto"], how="left")
display(df_merge.head(20))

,fecha,id_producto,cantidad_vendida,cliente_b2b,estado_orden,stock_cierre,almacen
0,2025-11-29,PROD-CEMENTO,108,RETAIL OMEGA,COMPLETADA,841,ALM-LIMA
1,2025-11-29,PROD-CEMENTO,108,RETAIL OMEGA,COMPLETADA,841,ALM-LIMA
2,2025-11-29,PROD-CEMENTO,108,INDEPENDIENTE,COMPLETADA,841,ALM-LIMA
3,2025-11-29,PROD-LADRILLO,112,INDEPENDIENTE,COMPLETADA,1392,ALM-LIMA
4,2025-11-29,PROD-LADRILLO,112,INDEPENDIENTE,COMPLETADA,1392,ALM-LIMA
5,2025-11-29,PROD-ACERO,423,CONSTRUCTORA ALFA,COMPLETADA,1515,ALM-LIMA
6,2025-11-29,PROD-ARENA,96,CONSTRUCTORA BETA,COMPLETADA,1050,ALM-CALLAO
7,2025-11-29,PROD-ARENA,96,CONSTRUCTORA BETA,COMPLETADA,1050,ALM-CALLAO
8,2025-11-29,PROD-ARENA,96,RETAIL OMEGA,COMPLETADA,1050,ALM-CALLAO
9,2025-11-30,PROD-CEMENTO,99,CONSTRUCTORA ALFA,COMPLETADA,1245,ALM-LIMA
10,2025-11-30,PROD-CEMENTO,99,RETAIL OMEGA,COMPLETADA,1245,ALM-LIMA
11,2025-11-30,PROD-CEMENTO,99,RETAIL OMEGA,COMPLETADA,1245,ALM-LIMA
12,2025-11-30,PROD-LADRILLO,92,INDEPENDIENTE,COMPLETADA,1043,ALM-CALLAO
13,2025-11-30,PROD-LADRILLO,92,RETAIL OMEGA,COMPLETADA,1043,ALM-CALLAO
14,2025-11-30,PROD-LADRILLO,92,INDEPENDIENTE,COMPLETADA,1043,ALM-CALLAO
15,2025-11-30,PROD-ACERO,101,CONSTRUCTORA BETA,COMPLETADA,1544,ALM-CALLAO
16,2025-11-30,PROD-ACERO,101,CONSTRUCTORA BETA,COMPLETADA,1544,ALM-CALLAO
17,2025-11-30,PROD-ARENA,123,INDEPENDIENTE,COMPLETADA,1195,ALM-CALLAO
18,2025-11-30,PROD-ARENA,123,CONSTRUCTORA BETA,COMPLETADA,1195,ALM-CALLAO
19,2025-11-30,PROD-ARENA,123,RETAIL OMEGA,COMPLETADA,1195,ALM-CALLAO

In [96]:
condicion_ventas = df_merge["cantidad_vendida"] == 0
condicion_stock = (df_merge["stock_cierre"] <= 0) | (df_merge["stock_cierre"].isna())
df_merge["quiebre_stock"] = np.where(condicion_ventas & condicion_stock, 1, 0)
display(df_merge.head(20))

,fecha,id_producto,cantidad_vendida,cliente_b2b,estado_orden,stock_cierre,almacen,quiebre_stock
0,2025-11-29,PROD-CEMENTO,108,RETAIL OMEGA,COMPLETADA,841,ALM-LIMA,0
1,2025-11-29,PROD-CEMENTO,108,RETAIL OMEGA,COMPLETADA,841,ALM-LIMA,0
2,2025-11-29,PROD-CEMENTO,108,INDEPENDIENTE,COMPLETADA,841,ALM-LIMA,0
3,2025-11-29,PROD-LADRILLO,112,INDEPENDIENTE,COMPLETADA,1392,ALM-LIMA,0
4,2025-11-29,PROD-LADRILLO,112,INDEPENDIENTE,COMPLETADA,1392,ALM-LIMA,0
5,2025-11-29,PROD-ACERO,423,CONSTRUCTORA ALFA,COMPLETADA,1515,ALM-LIMA,0
6,2025-11-29,PROD-ARENA,96,CONSTRUCTORA BETA,COMPLETADA,1050,ALM-CALLAO,0
7,2025-11-29,PROD-ARENA,96,CONSTRUCTORA BETA,COMPLETADA,1050,ALM-CALLAO,0
8,2025-11-29,PROD-ARENA,96,RETAIL OMEGA,COMPLETADA,1050,ALM-CALLAO,0
9,2025-11-30,PROD-CEMENTO,99,CONSTRUCTORA ALFA,COMPLETADA,1245,ALM-LIMA,0
10,2025-11-30,PROD-CEMENTO,99,RETAIL OMEGA,COMPLETADA,1245,ALM-LIMA,0
11,2025-11-30,PROD-CEMENTO,99,RETAIL OMEGA,COMPLETADA,1245,ALM-LIMA,0
12,2025-11-30,PROD-LADRILLO,92,INDEPENDIENTE,COMPLETADA,1043,ALM-CALLAO,0
13,2025-11-30,PROD-LADRILLO,92,RETAIL OMEGA,COMPLETADA,1043,ALM-CALLAO,0
14,2025-11-30,PROD-LADRILLO,92,INDEPENDIENTE,COMPLETADA,1043,ALM-CALLAO,0
15,2025-11-30,PROD-ACERO,101,CONSTRUCTORA BETA,COMPLETADA,1544,ALM-CALLAO,0
16,2025-11-30,PROD-ACERO,101,CONSTRUCTORA BETA,COMPLETADA,1544,ALM-CALLAO,0
17,2025-11-30,PROD-ARENA,123,INDEPENDIENTE,COMPLETADA,1195,ALM-CALLAO,0
18,2025-11-30,PROD-ARENA,123,CONSTRUCTORA BETA,COMPLETADA,1195,ALM-CALLAO,0
19,2025-11-30,PROD-ARENA,123,RETAIL OMEGA,COMPLETADA,1195,ALM-CALLAO,0

In [97]:
df_merge["ventas_sanas"] = np.where(df_merge["quiebre_stock"] == 1, np.nan, df_merge["cantidad_vendida"])
display(df_merge.head(20))

,fecha,id_producto,cantidad_vendida,cliente_b2b,estado_orden,stock_cierre,almacen,quiebre_stock,ventas_sanas
0,2025-11-29,PROD-CEMENTO,108,RETAIL OMEGA,COMPLETADA,841,ALM-LIMA,0,108.0
1,2025-11-29,PROD-CEMENTO,108,RETAIL OMEGA,COMPLETADA,841,ALM-LIMA,0,108.0
2,2025-11-29,PROD-CEMENTO,108,INDEPENDIENTE,COMPLETADA,841,ALM-LIMA,0,108.0
3,2025-11-29,PROD-LADRILLO,112,INDEPENDIENTE,COMPLETADA,1392,ALM-LIMA,0,112.0
4,2025-11-29,PROD-LADRILLO,112,INDEPENDIENTE,COMPLETADA,1392,ALM-LIMA,0,112.0
5,2025-11-29,PROD-ACERO,423,CONSTRUCTORA ALFA,COMPLETADA,1515,ALM-LIMA,0,423.0
6,2025-11-29,PROD-ARENA,96,CONSTRUCTORA BETA,COMPLETADA,1050,ALM-CALLAO,0,96.0
7,2025-11-29,PROD-ARENA,96,CONSTRUCTORA BETA,COMPLETADA,1050,ALM-CALLAO,0,96.0
8,2025-11-29,PROD-ARENA,96,RETAIL OMEGA,COMPLETADA,1050,ALM-CALLAO,0,96.0
9,2025-11-30,PROD-CEMENTO,99,CONSTRUCTORA ALFA,COMPLETADA,1245,ALM-LIMA,0,99.0
10,2025-11-30,PROD-CEMENTO,99,RETAIL OMEGA,COMPLETADA,1245,ALM-LIMA,0,99.0
11,2025-11-30,PROD-CEMENTO,99,RETAIL OMEGA,COMPLETADA,1245,ALM-LIMA,0,99.0
12,2025-11-30,PROD-LADRILLO,92,INDEPENDIENTE,COMPLETADA,1043,ALM-CALLAO,0,92.0
13,2025-11-30,PROD-LADRILLO,92,RETAIL OMEGA,COMPLETADA,1043,ALM-CALLAO,0,92.0
14,2025-11-30,PROD-LADRILLO,92,INDEPENDIENTE,COMPLETADA,1043,ALM-CALLAO,0,92.0
15,2025-11-30,PROD-ACERO,101,CONSTRUCTORA BETA,COMPLETADA,1544,ALM-CALLAO,0,101.0
16,2025-11-30,PROD-ACERO,101,CONSTRUCTORA BETA,COMPLETADA,1544,ALM-CALLAO,0,101.0
17,2025-11-30,PROD-ARENA,123,INDEPENDIENTE,COMPLETADA,1195,ALM-CALLAO,0,123.0
18,2025-11-30,PROD-ARENA,123,CONSTRUCTORA BETA,COMPLETADA,1195,ALM-CALLAO,0,123.0
19,2025-11-30,PROD-ARENA,123,RETAIL OMEGA,COMPLETADA,1195,ALM-CALLAO,0,123.0

In [98]:
promedio_historico = df_merge.groupby("id_producto")["ventas_sanas"].transform("mean").fillna(0).round().astype(int)
display(promedio_historico.head(20))

0     153
1     153
2     153
3     152
4     152
5     142
6     150
7     150
8     150
9     153
10    153
11    153
12    152
13    152
14    152
15    142
16    142
17    150
18    150
19    150
Name: ventas_sanas, dtype: int64

In [99]:
df_merge["demanda_no_restringida"] = np.where(df_merge["quiebre_stock"] == 1, promedio_historico, df_merge["ventas_sanas"])
df_merge = df_merge.drop(columns=["ventas_sanas"])
display(df_merge[["fecha", "id_producto", "cantidad_vendida", "quiebre_stock", "demanda_no_restringida"]].head(20))

,fecha,id_producto,cantidad_vendida,quiebre_stock,demanda_no_restringida
0,2025-11-29,PROD-CEMENTO,108,0,108.0
1,2025-11-29,PROD-CEMENTO,108,0,108.0
2,2025-11-29,PROD-CEMENTO,108,0,108.0
3,2025-11-29,PROD-LADRILLO,112,0,112.0
4,2025-11-29,PROD-LADRILLO,112,0,112.0
5,2025-11-29,PROD-ACERO,423,0,423.0
6,2025-11-29,PROD-ARENA,96,0,96.0
7,2025-11-29,PROD-ARENA,96,0,96.0
8,2025-11-29,PROD-ARENA,96,0,96.0
9,2025-11-30,PROD-CEMENTO,99,0,99.0
10,2025-11-30,PROD-CEMENTO,99,0,99.0
11,2025-11-30,PROD-CEMENTO,99,0,99.0
12,2025-11-30,PROD-LADRILLO,92,0,92.0
13,2025-11-30,PROD-LADRILLO,92,0,92.0
14,2025-11-30,PROD-LADRILLO,92,0,92.0
15,2025-11-30,PROD-ACERO,101,0,101.0
16,2025-11-30,PROD-ACERO,101,0,101.0
17,2025-11-30,PROD-ARENA,123,0,123.0
18,2025-11-30,PROD-ARENA,123,0,123.0
19,2025-11-30,PROD-ARENA,123,0,123.0